const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTURSdTVQNit1amdyUG5LbDRyaHB5TGVicjROUEg3YSt2eXlrSmt6Mmpuaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNE9zTXp5NmNpemJGQ2NtZW5QaURyYmVGWnFGNEVuU2swM3ZvZVF0ZVZ6cz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJrR0tkUjc1YlJQNTYvdmZ0TlptNGthdWxjQjVjMkgzblhYYTlWWjhheDJjPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJESlE0b3dvRThvUW9xbks0QzNPaWNRTnAwRmN4eE9kdTcxT2paS3psT0Y4PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IktLN3JHQSt5RjViMy9qSGdiRkpLaEd0aHpyQjB4c29jVDdLRk04N3B1M0k9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InBOT1hIRFRzeHNNd2NVLzJsR3RNc1JXT25mTDdKMVpaMll2alp4VkxSV2M9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT0VzRkxOQUZGVUcxUGRCc1Nzek8rc2hMOXMwMDZWQlcvRlE3Z3g3a1BsND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiekh4K1BFd0gxRVBXNGRWeVphWkdKWitTV214aThzU3FqaUdlTWhkRm54Yz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InZZZDd0ZTc3b2tMVmFkcTRjdTE2V2pDQXZsZUwrVEh3Z1AzU01PK243cGJhZUlCZ3l3VXVXTnJGaWZwUmNobkNHa1krRUZYYkI0V0paN0tuK2dmNERnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTg0LCJhZHZTZWNyZXRLZXkiOiJyM0NLT1QwS3AzajFSZlhiMklLZE95OVlvOXdLd1A1SUhTdVBMRFFiSDgwPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjIzNDkxNjc2Njg4NzRAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiM0YzRDA3MzhCMTI0QjY5QjdGRThFN0E2MzY5QzFFQTIifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc0MzA3Mzk3NX0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjM0OTE2NzY2ODg3NEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI5NkQ1RDUzMjM0QURCN0IzNTM2MEQ3RDYzQTUyOTA0MiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzQzMDczOTc1fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJ5eVBlVTJHR1M1S0RlTGdaaEM1OThRIiwicGhvbmVJZCI6IjVjMWNiMmY3LTJhMGUtNDU0NS1hMWIwLTNmYmU5NWYxZjViMSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJlb0MvOXBFWWJlQSt0QW1HcFJtNWVRZHBwd0E9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWDQvWHFoK3RVNUh5TDV3WDVDOWJOc1pqR2lBPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IlE2S1AyWUVUIiwibWUiOnsiaWQiOiIyMzQ5MTY3NjY4ODc0OjM5QHMud2hhdHNhcHAubmV0IiwibmFtZSI6Ik9tYWxlfjI2In0sImFjY291bnQiOnsiZGV0YWlscyI6IkNQT1pxcElCRUtMbGxMOEdHQUlnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJEcnFOL2VXSkYyQlpMRVNYSzVZcG1VQXJvQ2FqTkIxeUVrZm13TlhIRHpvPSIsImFjY291bnRTaWduYXR1cmUiOiJpZ1ZFc1lxQ2VsSWtmUDkxWG91OTJaWk9GZmtJdGgvZEdJWllUMnAxQURrdWRxbGlZNFo0Ly9tcGhWM0UvWFp5K3V0SGp6c0dMa2VMZFpkaHlCYmpBdz09IiwiZGV2aWNlU2lnbmF0dXJlIjoicTlQNzRpVm5qUGthSGhFczBidEgwNVNheHpLU1J4Q3FOcHJNRkNXNDhWZS9MMSs4WWNWNDB1LzRwaVdOcEt0cUVLdWJGNGE0N3ZnMzRCbmRxSG9MQ3c9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMzQ5MTY3NjY4ODc0OjM5QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlE2NmpmM2xpUmRnV1N4RWx5dVdLWmxBSzZBbW96UWRjaEpINXNEVnh3ODYifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NDMwNzM5NjcsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBT2FXIn0=",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
